### ISSUE TITLE
d i s c u s s i o n s

### ISSUE THREAD

**Issue by Suyashtnt** [hYdos/fabric-language-c#2]
i mean just click a button so we can discuss the concernness/amazingness of this mod

**Comment by ramidzkh** [comment]
@hYdos's mod `fabric-language-c` would contribute to a desperately needed class of Minecraft mods which utilize the core system components of the user, while maintaining a somewhat sane connection to the JVM and the running instance of Minecraft.

wait no this project is stale

**Comment by OakBricks** [comment]
this is a ***very*** cursed mod

**Comment by hYdos** [comment]
> @hYdos's mod `fabric-language-c` would contribute to a desperately needed class of Minecraft mods which utilize the core system components of the user, while maintaining a somewhat sane connection to the JVM and the running instance of Minecraft.
> 
> wait no this project is stale

not for long

**Comment by hYdos** [comment]
it has been done
